import { RootProviders } from '@/app/RootProviders';
import { auth } from '@/lib/auth';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';
import type { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout ({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const me = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
    <head>
      <link rel="icon" href="/favicon.svg" sizes="any" />
    </head>
    <body className={inter.className}>
    <RootProviders me={me}>
      {children}
    </RootProviders>
    <Script async src='/widget.js' />
    </body>
    </html>
  );
}
