"""empty message

Revision ID: 00534dc350db
Revises: 10f36e8a25c4
Create Date: 2024-08-26 12:46:00.203425

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00534dc350db"
down_revision = "10f36e8a25c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embedding_models",
        "provider",
        existing_type=mysql.ENUM("OPENAI"),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "llms",
        "provider",
        existing_type=mysql.ENUM(
            "OPENAI", "GEMINI", "ANTHROPIC_VERTEX", "OPENAI_LIKE", "BEDROCK"
        ),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        "reranker_models",
        "provider",
        existing_type=mysql.ENUM("JINA", "COHERE", "BAISHENG"),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.execute("UPDATE embedding_models SET provider = lower(provider)")
    op.execute("UPDATE llms SET provider = lower(provider)")
    op.execute("UPDATE reranker_models SET provider = lower(provider)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reranker_models",
        "provider",
        existing_type=sa.String(length=32),
        type_=mysql.ENUM("JINA", "COHERE", "BAISHENG"),
        existing_nullable=False,
    )
    op.alter_column(
        "llms",
        "provider",
        existing_type=sa.String(length=32),
        type_=mysql.ENUM(
            "OPENAI", "GEMINI", "ANTHROPIC_VERTEX", "OPENAI_LIKE", "BEDROCK"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "embedding_models",
        "provider",
        existing_type=sa.String(length=32),
        type_=mysql.ENUM("OPENAI"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
