"""empty message

Revision ID: 0a9a86063372
Revises: 7b40dab31ebd
Create Date: 2024-07-02 14:34:26.917863

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0a9a86063372"
down_revision = "7b40dab31ebd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("sources", sa.JSON(), nullable=True))
    op.alter_column(
        "chats",
        "engine_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chats",
        "engine_id",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    op.drop_column("chat_messages", "sources")
    # ### end Alembic commands ###
