"""empty message

Revision ID: 10f36e8a25c4
Revises: 041fbef26e3a
Create Date: 2024-08-20 09:10:50.130219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10f36e8a25c4'
down_revision = '041fbef26e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reranker_models",
        "provider",
        existing_type=mysql.ENUM(
            "JINA", "COHERE", "BAISHENG"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "reranker_models",
        "provider",
        existing_type=mysql.ENUM(
            "JINA", "COHERE"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
