"""empty message

Revision ID: 2fc10c21bf88
Revises: 8248a83756fd
Create Date: 2024-07-07 06:14:43.743558

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "2fc10c21bf88"
down_revision = "8248a83756fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "site_settings", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "site_settings", type_="unique")
    # ### end Alembic commands ###
