"""empty message

Revision ID: 40e9c98fa559
Revises: 0a9a86063372
Create Date: 2024-07-03 08:55:07.759140

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "40e9c98fa559"
down_revision = "0a9a86063372"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("meta", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "meta")
    # ### end Alembic commands ###
