"""empty message

Revision ID: 7b40dab31ebd
Revises: fdf09af57edd
Create Date: 2024-07-02 08:46:06.195050

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "7b40dab31ebd"
down_revision = "fdf09af57edd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    op.create_foreign_key(None, "chat_messages", "users", ["user_id"], ["id"])
    op.add_column(
        "chats", sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=True)
    )
    op.create_foreign_key(None, "chats", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "user_id")
    op.drop_column("chat_messages", "user_id")
    # ### end Alembic commands ###
