"""empty message

Revision ID: 893aff1b8621
Revises: 680a9c5abc04
Create Date: 2024-07-03 11:14:46.645865

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "893aff1b8621"
down_revision = "680a9c5abc04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column(
            "index_status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="kgindexstatus",
            ),
            nullable=False,
        ),
    )
    op.add_column("chunks", sa.Column("index_result", sa.Text(), nullable=True))
    op.add_column(
        "documents",
        sa.Column(
            "index_status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="docindextaskstatus",
            ),
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("index_result", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "documents", ["source_uri"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_column("documents", "index_result")
    op.drop_column("documents", "index_status")
    op.drop_column("chunks", "index_result")
    op.drop_column("chunks", "index_status")
    # ### end Alembic commands ###
