"""empty message

Revision ID: bd17a4ebccc5
Revises: a8c79553c9f6
Create Date: 2024-08-08 01:20:42.069228

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "bd17a4ebccc5"
down_revision = "a8c79553c9f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_sources", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_index("source_uri", table_name="documents")
    op.add_column(
        "relationships",
        sa.Column("chunk_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("relationships", "chunk_id")
    op.create_index("source_uri", "documents", ["source_uri"], unique=True)
    op.drop_column("data_sources", "deleted_at")
    # ### end Alembic commands ###
