"""empty message

Revision ID: bedd6334a769
Revises: b2b931d629f5
Create Date: 2024-06-30 23:57:18.743181

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = 'bedd6334a769'
down_revision = 'b2b931d629f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_1', 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint('fk_1', 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'chat_engines', ['engine_id'], ['id'])
    op.drop_constraint('fk_1', 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'])
    op.drop_constraint('fk_1', 'relationships', type_='foreignkey')
    op.drop_constraint('fk_2', 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'entities', ['source_entity_id'], ['id'])
    op.create_foreign_key(None, 'relationships', 'entities', ['target_entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key('fk_2', 'relationships', 'entities', ['target_entity_id'], ['id'], referent_schema='test')
    op.create_foreign_key('fk_1', 'relationships', 'entities', ['source_entity_id'], ['id'], referent_schema='test')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key('fk_1', 'chunks', 'documents', ['document_id'], ['id'], referent_schema='test')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key('fk_1', 'chats', 'chat_engines', ['engine_id'], ['id'], referent_schema='test')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key('fk_1', 'chat_messages', 'chats', ['chat_id'], ['id'], referent_schema='test')
    # ### end Alembic commands ###
