"""empty message

Revision ID: d9c17a1ed3f7
Revises: c24984705d42
Create Date: 2024-07-05 06:05:16.292744

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType


# revision identifiers, used by Alembic.
revision = "d9c17a1ed3f7"
down_revision = "c24984705d42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "semantic_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column(
            "query_vec",
            VectorType(dim=1536),
            nullable=True,
            comment="hnsw(distance=cosine)",
        ),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column(
            "value_vec",
            VectorType(dim=1536),
            nullable=True,
            comment="hnsw(distance=cosine)",
        ),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_TTL="created_at + INTERVAL 1 MONTH;",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("semantic_cache")
    # ### end Alembic commands ###
