"""empty message

Revision ID: dfee070b8abd
Revises: eb0b85608c0a
Create Date: 2024-09-10 10:45:50.318277

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from tidb_vector.sqlalchemy import VectorType
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dfee070b8abd'
down_revision = 'eb0b85608c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('graph_data', sa.JSON(), nullable=True))
    op.create_index('idx_entity_type', 'entities', ['entity_type'], unique=False)
    op.alter_column('site_settings', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.alter_column('site_settings', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_settings', 'updated_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'))
    op.alter_column('site_settings', 'created_at',
               existing_type=mysql.DATETIME(fsp=6),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(6)'))
    op.drop_index('idx_entity_type', table_name='entities')
    op.drop_column('chat_messages', 'graph_data')
    # ### end Alembic commands ###
